name: Deploy
on:
  push:
    branches:
      - main
  repository_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: yarn
      - name: Install build dependencies
        run: yarn install --frozen-lockfile --production
      - name: Build static files
        run: yarn build
        env:
          FORCE_COLOR: 2
          GITTER_TOKEN: ${{ secrets.GITTER_TOKEN }}
          GITTER_ROOM_ID: ${{ secrets.GITTER_ROOM_ID }}
      - name: Check files changes
        id: hash
        run: npx ssdeploy changed
        env:
          FORCE_COLOR: 2
          WEBSITE_URL: ${{ secrets.WEBSITE_URL }}
      - name: Install Google Cloud
        if: "!steps.hash.outputs.noChanges"
        uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCLOUD_AUTH }}
      - name: Deploy files
        if: "!steps.hash.outputs.noChanges"
        run: npx ssdeploy deploy --verbose
        env:
          GCLOUD_APP: ${{ secrets.GCLOUD_APP }}
          GCLOUD_PROJECT: ${{ secrets.GCLOUD_PROJECT }}
          CLOUDFLARE_ZONE: ${{ secrets.CLOUDFLARE_ZONE }}
          CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
      - name: Warm CDN
        if: "!steps.hash.outputs.noChanges"
        run: wget --page-requisites https://logux.io
      - name: Audit website
        if: "!steps.hash.outputs.noChanges"
        uses: treosh/lighthouse-ci-action@v7
        with:
          runs: 3
          uploadArtifacts: true
          temporaryPublicStorage: true
          configPath: ./lighthouserc.json
